require("dotenv").config();
const mongoose = require("mongoose");
const Medicine = require("../models/Medicine");

const departmentMedicines = {
  Neurology: {
    category: "Neurological",
    medicines: [
      {
        name: "Sodium Valproate",
        genericName: "Sodium Valproate",
        strength: "250mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Sodium Valproate",
        genericName: "Sodium Valproate",
        strength: "500mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Phenytoin",
        genericName: "Phenytoin",
        strength: "50mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Phenytoin",
        genericName: "Phenytoin",
        strength: "100mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Carbamazepine",
        genericName: "Carbamazepine",
        strength: "200mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Carbamazepine",
        genericName: "Carbamazepine",
        strength: "400mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Levetiracetam",
        genericName: "Levetiracetam",
        strength: "250mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Levetiracetam",
        genericName: "Levetiracetam",
        strength: "500mg",
        form: "Tablet",
        price: 350,
      },
      {
        name: "Levetiracetam",
        genericName: "Levetiracetam",
        strength: "1000mg",
        form: "Tablet",
        price: 600,
      },
      {
        name: "Lamotrigine",
        genericName: "Lamotrigine",
        strength: "25mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Lamotrigine",
        genericName: "Lamotrigine",
        strength: "50mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Lamotrigine",
        genericName: "Lamotrigine",
        strength: "100mg",
        form: "Tablet",
        price: 350,
      },
      {
        name: "Gabapentin",
        genericName: "Gabapentin",
        strength: "300mg",
        form: "Capsule",
        price: 180,
      },
      {
        name: "Gabapentin",
        genericName: "Gabapentin",
        strength: "400mg",
        form: "Capsule",
        price: 220,
      },
      {
        name: "Pregabalin",
        genericName: "Pregabalin",
        strength: "75mg",
        form: "Capsule",
        price: 250,
      },
      {
        name: "Pregabalin",
        genericName: "Pregabalin",
        strength: "150mg",
        form: "Capsule",
        price: 400,
      },
      {
        name: "Diazepam",
        genericName: "Diazepam",
        strength: "5mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Diazepam",
        genericName: "Diazepam",
        strength: "10mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Diazepam",
        genericName: "Diazepam",
        strength: "10mg",
        form: "Injection",
        price: 150,
      },
      {
        name: "Lorazepam",
        genericName: "Lorazepam",
        strength: "1mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Lorazepam",
        genericName: "Lorazepam",
        strength: "2mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Midazolam",
        genericName: "Midazolam",
        strength: "5mg/ml",
        form: "Injection",
        price: 200,
      },
      {
        name: "Amitriptyline",
        genericName: "Amitriptyline",
        strength: "25mg",
        form: "Tablet",
        price: 70,
      },
      {
        name: "Fluoxetine",
        genericName: "Fluoxetine",
        strength: "20mg",
        form: "Capsule",
        price: 120,
      },
      {
        name: "Sertraline",
        genericName: "Sertraline",
        strength: "50mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Escitalopram",
        genericName: "Escitalopram",
        strength: "10mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Risperidone",
        genericName: "Risperidone",
        strength: "2mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Haloperidol",
        genericName: "Haloperidol",
        strength: "5mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Donepezil",
        genericName: "Donepezil",
        strength: "5mg",
        form: "Tablet",
        price: 300,
      },
      {
        name: "Memantine",
        genericName: "Memantine",
        strength: "10mg",
        form: "Tablet",
        price: 350,
      },
      {
        name: "Levodopa + Carbidopa",
        genericName: "Levodopa + Carbidopa",
        strength: "250mg/25mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Citicoline",
        genericName: "Citicoline",
        strength: "500mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Citicoline",
        genericName: "Citicoline",
        strength: "500mg",
        form: "Injection",
        price: 350,
      },
      {
        name: "Pyridoxine (B6)",
        genericName: "Pyridoxine",
        strength: "50mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Sumatriptan",
        genericName: "Sumatriptan",
        strength: "50mg",
        form: "Tablet",
        price: 300,
      },
      {
        name: "Topiramate",
        genericName: "Topiramate",
        strength: "25mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Baclofen",
        genericName: "Baclofen",
        strength: "10mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Propranolol",
        genericName: "Propranolol",
        strength: "40mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Phenobarbital",
        genericName: "Phenobarbital",
        strength: "60mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Clonazepam",
        genericName: "Clonazepam",
        strength: "0.5mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Alprazolam",
        genericName: "Alprazolam",
        strength: "0.5mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Olanzapine",
        genericName: "Olanzapine",
        strength: "5mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Quetiapine",
        genericName: "Quetiapine",
        strength: "100mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Lithium Carbonate",
        genericName: "Lithium Carbonate",
        strength: "300mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Thiamine (B1)",
        genericName: "Thiamine",
        strength: "100mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Oxcarbazepine",
        genericName: "Oxcarbazepine",
        strength: "300mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Venlafaxine",
        genericName: "Venlafaxine",
        strength: "75mg",
        form: "Capsule",
        price: 220,
      },
    ],
  },
  Cardiology: {
    category: "Cardiovascular",
    medicines: [
      {
        name: "Aspirin",
        genericName: "Aspirin",
        strength: "75mg",
        form: "Tablet",
        price: 30,
      },
      {
        name: "Aspirin",
        genericName: "Aspirin",
        strength: "150mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Aspirin",
        genericName: "Aspirin",
        strength: "300mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Clopidogrel",
        genericName: "Clopidogrel",
        strength: "75mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Atorvastatin",
        genericName: "Atorvastatin",
        strength: "10mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Atorvastatin",
        genericName: "Atorvastatin",
        strength: "20mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Atorvastatin",
        genericName: "Atorvastatin",
        strength: "40mg",
        form: "Tablet",
        price: 400,
      },
      {
        name: "Rosuvastatin",
        genericName: "Rosuvastatin",
        strength: "5mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Rosuvastatin",
        genericName: "Rosuvastatin",
        strength: "10mg",
        form: "Tablet",
        price: 300,
      },
      {
        name: "Rosuvastatin",
        genericName: "Rosuvastatin",
        strength: "20mg",
        form: "Tablet",
        price: 500,
      },
      {
        name: "Amlodipine",
        genericName: "Amlodipine",
        strength: "5mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Amlodipine",
        genericName: "Amlodipine",
        strength: "10mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Atenolol",
        genericName: "Atenolol",
        strength: "50mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Metoprolol",
        genericName: "Metoprolol",
        strength: "25mg",
        form: "Tablet",
        price: 70,
      },
      {
        name: "Metoprolol",
        genericName: "Metoprolol",
        strength: "50mg",
        form: "Tablet",
        price: 110,
      },
      {
        name: "Bisoprolol",
        genericName: "Bisoprolol",
        strength: "2.5mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Bisoprolol",
        genericName: "Bisoprolol",
        strength: "5mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Carvedilol",
        genericName: "Carvedilol",
        strength: "6.25mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Enalapril",
        genericName: "Enalapril",
        strength: "5mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Lisinopril",
        genericName: "Lisinopril",
        strength: "5mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Losartan",
        genericName: "Losartan",
        strength: "25mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Losartan",
        genericName: "Losartan",
        strength: "50mg",
        form: "Tablet",
        price: 160,
      },
      {
        name: "Telmisartan",
        genericName: "Telmisartan",
        strength: "40mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Telmisartan",
        genericName: "Telmisartan",
        strength: "80mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Digoxin",
        genericName: "Digoxin",
        strength: "0.25mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Digoxin",
        genericName: "Digoxin",
        strength: "0.5mg",
        form: "Injection",
        price: 120,
      },
      {
        name: "Amiodarone",
        genericName: "Amiodarone",
        strength: "200mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Isosorbide Dinitrate",
        genericName: "Isosorbide Dinitrate",
        strength: "5mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Nitroglycerin",
        genericName: "Nitroglycerin",
        strength: "0.5mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Spironolactone",
        genericName: "Spironolactone",
        strength: "25mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Furosemide",
        genericName: "Furosemide",
        strength: "40mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Furosemide",
        genericName: "Furosemide",
        strength: "20mg",
        form: "Injection",
        price: 100,
      },
      {
        name: "Hydrochlorothiazide",
        genericName: "Hydrochlorothiazide",
        strength: "25mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Warfarin",
        genericName: "Warfarin",
        strength: "5mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Heparin",
        genericName: "Heparin",
        strength: "5000IU",
        form: "Injection",
        price: 200,
      },
      {
        name: "Enoxaparin",
        genericName: "Enoxaparin",
        strength: "40mg",
        form: "Injection",
        price: 500,
      },
      {
        name: "Rivaroxaban",
        genericName: "Rivaroxaban",
        strength: "10mg",
        form: "Tablet",
        price: 400,
      },
      {
        name: "Adrenaline",
        genericName: "Adrenaline",
        strength: "1mg/ml",
        form: "Injection",
        price: 150,
      },
      {
        name: "Atropine",
        genericName: "Atropine",
        strength: "0.6mg",
        form: "Injection",
        price: 80,
      },
      {
        name: "Verapamil",
        genericName: "Verapamil",
        strength: "80mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Diltiazem",
        genericName: "Diltiazem",
        strength: "60mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Simvastatin",
        genericName: "Simvastatin",
        strength: "20mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Ramipril",
        genericName: "Ramipril",
        strength: "5mg",
        form: "Tablet",
        price: 110,
      },
    ],
  },
  Orthopedics: {
    category: "Painkiller",
    medicines: [
      {
        name: "Ibuprofen",
        genericName: "Ibuprofen",
        strength: "200mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Ibuprofen",
        genericName: "Ibuprofen",
        strength: "400mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Ibuprofen",
        genericName: "Ibuprofen",
        strength: "600mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Naproxen",
        genericName: "Naproxen",
        strength: "250mg",
        form: "Tablet",
        price: 70,
      },
      {
        name: "Naproxen",
        genericName: "Naproxen",
        strength: "500mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Diclofenac Sodium",
        genericName: "Diclofenac Sodium",
        strength: "50mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Diclofenac Sodium",
        genericName: "Diclofenac Sodium",
        strength: "1%",
        form: "Gel",
        price: 150,
      },
      {
        name: "Diclofenac Sodium",
        genericName: "Diclofenac Sodium",
        strength: "75mg",
        form: "Injection",
        price: 100,
      },
      {
        name: "Aceclofenac",
        genericName: "Aceclofenac",
        strength: "100mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Celecoxib",
        genericName: "Celecoxib",
        strength: "100mg",
        form: "Capsule",
        price: 150,
      },
      {
        name: "Celecoxib",
        genericName: "Celecoxib",
        strength: "200mg",
        form: "Capsule",
        price: 250,
      },
      {
        name: "Etoricoxib",
        genericName: "Etoricoxib",
        strength: "60mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Etoricoxib",
        genericName: "Etoricoxib",
        strength: "90mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Etoricoxib",
        genericName: "Etoricoxib",
        strength: "120mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Tramadol",
        genericName: "Tramadol",
        strength: "50mg",
        form: "Capsule",
        price: 100,
      },
      {
        name: "Tramadol",
        genericName: "Tramadol",
        strength: "100mg",
        form: "Capsule",
        price: 180,
      },
      {
        name: "Morphine",
        genericName: "Morphine",
        strength: "10mg/ml",
        form: "Injection",
        price: 300,
      },
      {
        name: "Calcium Carbonate",
        genericName: "Calcium Carbonate",
        strength: "500mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Vitamin D3",
        genericName: "Cholecalciferol",
        strength: "60000IU",
        form: "Capsule",
        price: 50,
      },
      {
        name: "Glucosamine",
        genericName: "Glucosamine",
        strength: "500mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Chondroitin",
        genericName: "Chondroitin",
        strength: "400mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Alendronate",
        genericName: "Alendronate",
        strength: "70mg",
        form: "Tablet",
        price: 300,
      },
      {
        name: "Methotrexate",
        genericName: "Methotrexate",
        strength: "7.5mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Hydroxychloroquine",
        genericName: "Hydroxychloroquine",
        strength: "200mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Allopurinol",
        genericName: "Allopurinol",
        strength: "100mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Allopurinol",
        genericName: "Allopurinol",
        strength: "300mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Colchicine",
        genericName: "Colchicine",
        strength: "0.5mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Methylprednisolone",
        genericName: "Methylprednisolone",
        strength: "40mg",
        form: "Injection",
        price: 200,
      },
      {
        name: "Dexamethasone",
        genericName: "Dexamethasone",
        strength: "4mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Lignocaine",
        genericName: "Lignocaine",
        strength: "2%",
        form: "Injection",
        price: 100,
      },
      {
        name: "Pantoprazole",
        genericName: "Pantoprazole",
        strength: "40mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Piroxicam",
        genericName: "Piroxicam",
        strength: "20mg",
        form: "Tablet",
        price: 90,
      },
      {
        name: "Calcitriol",
        genericName: "Calcitriol",
        strength: "0.25mcg",
        form: "Capsule",
        price: 150,
      },
    ],
  },
  ENT: {
    category: "Antibiotic",
    medicines: [
      {
        name: "Co-Amoxiclav",
        genericName: "Amoxicillin + Clavulanate",
        strength: "375mg",
        form: "Tablet",
        price: 150,
      },
      {
        name: "Co-Amoxiclav",
        genericName: "Amoxicillin + Clavulanate",
        strength: "625mg",
        form: "Tablet",
        price: 250,
      },
      {
        name: "Cefixime",
        genericName: "Cefixime",
        strength: "200mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Cefixime",
        genericName: "Cefixime",
        strength: "400mg",
        form: "Tablet",
        price: 350,
      },
      {
        name: "Azithromycin",
        genericName: "Azithromycin",
        strength: "500mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Clarithromycin",
        genericName: "Clarithromycin",
        strength: "250mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Ciprofloxacin Drops",
        genericName: "Ciprofloxacin",
        strength: "0.3%",
        form: "Drops",
        price: 120,
      },
      {
        name: "Gentamicin Drops",
        genericName: "Gentamicin",
        strength: "0.3%",
        form: "Drops",
        price: 100,
      },
      {
        name: "Betamethasone Drops",
        genericName: "Betamethasone",
        strength: "0.1%",
        form: "Drops",
        price: 150,
      },
      {
        name: "Xylometazoline Nasal",
        genericName: "Xylometazoline",
        strength: "0.1%",
        form: "Spray",
        price: 100,
      },
      {
        name: "Fluticasone Spray",
        genericName: "Fluticasone",
        strength: "50mcg",
        form: "Spray",
        price: 400,
      },
      {
        name: "Mometasone Spray",
        genericName: "Mometasone",
        strength: "50mcg",
        form: "Spray",
        price: 450,
      },
      {
        name: "Loratadine",
        genericName: "Loratadine",
        strength: "10mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Cetirizine",
        genericName: "Cetirizine",
        strength: "10mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Fexofenadine",
        genericName: "Fexofenadine",
        strength: "120mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Fexofenadine",
        genericName: "Fexofenadine",
        strength: "180mg",
        form: "Tablet",
        price: 180,
      },
      {
        name: "Montelukast",
        genericName: "Montelukast",
        strength: "10mg",
        form: "Tablet",
        price: 200,
      },
      {
        name: "Levocetirizine",
        genericName: "Levocetirizine",
        strength: "5mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Guaifenesin",
        genericName: "Guaifenesin",
        strength: "100mg",
        form: "Syrup",
        price: 120,
      },
      {
        name: "Dextromethorphan",
        genericName: "Dextromethorphan",
        strength: "15mg",
        form: "Syrup",
        price: 100,
      },
      {
        name: "Chlorpheniramine",
        genericName: "Chlorpheniramine",
        strength: "4mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Nystatin Drops",
        genericName: "Nystatin",
        strength: "100000IU/ml",
        form: "Drops",
        price: 150,
      },
      {
        name: "Fluconazole",
        genericName: "Fluconazole",
        strength: "150mg",
        form: "Capsule",
        price: 120,
      },
      {
        name: "Povidone-Iodine Gargle",
        genericName: "Povidone-Iodine",
        strength: "2%",
        form: "Solution",
        price: 80,
      },
      {
        name: "Ambroxol",
        genericName: "Ambroxol",
        strength: "30mg",
        form: "Tablet",
        price: 70,
      },
      {
        name: "Bromhexine",
        genericName: "Bromhexine",
        strength: "8mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Prednisolone",
        genericName: "Prednisolone",
        strength: "5mg",
        form: "Tablet",
        price: 50,
      },
    ],
  },
  Radiology: {
    category: "Contrast Media",
    medicines: [
      {
        name: "Iohexol (Omnipaque)",
        genericName: "Iohexol",
        strength: "350mg/ml",
        form: "Injection",
        price: 2500,
      },
      {
        name: "Iopromide (Ultravist)",
        genericName: "Iopromide",
        strength: "370mg/ml",
        form: "Injection",
        price: 2800,
      },
      {
        name: "Barium Sulfate",
        genericName: "Barium Sulfate",
        strength: "100%",
        form: "Suspension",
        price: 500,
      },
      {
        name: "Buscopan",
        genericName: "Hyoscine",
        strength: "20mg",
        form: "Injection",
        price: 150,
      },
      {
        name: "Glucagon",
        genericName: "Glucagon",
        strength: "1mg",
        form: "Injection",
        price: 800,
      },
      {
        name: "Normal Saline",
        genericName: "Sodium Chloride",
        strength: "0.9%",
        form: "Solution",
        price: 50,
      },
      {
        name: "Hydrocortisone Inj",
        genericName: "Hydrocortisone",
        strength: "100mg",
        form: "Injection",
        price: 150,
      },
      {
        name: "Adrenaline Inj",
        genericName: "Adrenaline",
        strength: "1mg/ml",
        form: "Injection",
        price: 150,
      },
      {
        name: "Pheniramine (Avil)",
        genericName: "Pheniramine",
        strength: "45.5mg",
        form: "Injection",
        price: 80,
      },
      {
        name: "Atropine Inj",
        genericName: "Atropine",
        strength: "0.6mg",
        form: "Injection",
        price: 80,
      },
      {
        name: "Diphenhydramine",
        genericName: "Diphenhydramine",
        strength: "25mg",
        form: "Injection",
        price: 100,
      },
      {
        name: "Methylprednisolone Inj",
        genericName: "Methylprednisolone",
        strength: "40mg",
        form: "Injection",
        price: 200,
      },
      {
        name: "Sodium Bicarbonate",
        genericName: "Sodium Bicarbonate",
        strength: "8.4%",
        form: "Injection",
        price: 120,
      },
      {
        name: "Calcium Gluconate",
        genericName: "Calcium Gluconate",
        strength: "10%",
        form: "Injection",
        price: 100,
      },
    ],
  },
  Pediatrics: {
    category: "Vitamin",
    medicines: [
      {
        name: "Paracetamol Syrup",
        genericName: "Paracetamol",
        strength: "120mg/5ml",
        form: "Syrup",
        price: 80,
      },
      {
        name: "Paracetamol Drops",
        genericName: "Paracetamol",
        strength: "100mg/ml",
        form: "Drops",
        price: 100,
      },
      {
        name: "Ibuprofen Syrup",
        genericName: "Ibuprofen",
        strength: "100mg/5ml",
        form: "Syrup",
        price: 120,
      },
      {
        name: "Zinc Sulfate Syrup",
        genericName: "Zinc Sulfate",
        strength: "20mg/5ml",
        form: "Syrup",
        price: 80,
      },
      {
        name: "ORS Sachets",
        genericName: "Oral Rehydration Salts",
        strength: "27.9g",
        form: "Sachet",
        price: 20,
      },
      {
        name: "Domperidone Drops",
        genericName: "Domperidone",
        strength: "1mg/ml",
        form: "Drops",
        price: 100,
      },
      {
        name: "Simethicone Drops",
        genericName: "Simethicone",
        strength: "40mg/ml",
        form: "Drops",
        price: 120,
      },
      {
        name: "Salbutamol Syrup",
        genericName: "Salbutamol",
        strength: "2mg/5ml",
        form: "Syrup",
        price: 100,
      },
      {
        name: "Budesonide Respules",
        genericName: "Budesonide",
        strength: "0.5mg",
        form: "Respules",
        price: 200,
      },
      {
        name: "Amoxicillin Suspension",
        genericName: "Amoxicillin",
        strength: "125mg/5ml",
        form: "Suspension",
        price: 150,
      },
      {
        name: "Cefixime Suspension",
        genericName: "Cefixime",
        strength: "100mg/5ml",
        form: "Suspension",
        price: 250,
      },
      {
        name: "Metronidazole Syrup",
        genericName: "Metronidazole",
        strength: "200mg/5ml",
        form: "Syrup",
        price: 100,
      },
      {
        name: "Nystatin Oral Drops",
        genericName: "Nystatin",
        strength: "100000IU/ml",
        form: "Drops",
        price: 150,
      },
      {
        name: "Vitamin D3 Drops",
        genericName: "Cholecalciferol",
        strength: "400IU/drop",
        form: "Drops",
        price: 200,
      },
      {
        name: "Multi-vitamin Syrup",
        genericName: "Multi-vitamin",
        strength: "Various",
        form: "Syrup",
        price: 180,
      },
      {
        name: "Iron Drops",
        genericName: "Ferrous Sulfate",
        strength: "25mg/ml",
        form: "Drops",
        price: 120,
      },
      {
        name: "Folic Acid",
        genericName: "Folic Acid",
        strength: "5mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Albendazole",
        genericName: "Albendazole",
        strength: "400mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Mebendazole",
        genericName: "Mebendazole",
        strength: "100mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Prednisolone Syrup",
        genericName: "Prednisolone",
        strength: "5mg/5ml",
        form: "Syrup",
        price: 150,
      },
      {
        name: "Zinc Oxide Cream",
        genericName: "Zinc Oxide",
        strength: "20%",
        form: "Cream",
        price: 80,
      },
      {
        name: "Glycerin Suppository",
        genericName: "Glycerin",
        strength: "1g",
        form: "Suppository",
        price: 50,
      },
      {
        name: "Lactulose Syrup",
        genericName: "Lactulose",
        strength: "3.3g/5ml",
        form: "Syrup",
        price: 200,
      },
    ],
  },
  General: {
    category: "Gastrointestinal",
    medicines: [
      {
        name: "Omeprazole",
        genericName: "Omeprazole",
        strength: "20mg",
        form: "Capsule",
        price: 80,
      },
      {
        name: "Omeprazole",
        genericName: "Omeprazole",
        strength: "40mg",
        form: "Capsule",
        price: 120,
      },
      {
        name: "Esomeprazole",
        genericName: "Esomeprazole",
        strength: "40mg",
        form: "Capsule",
        price: 150,
      },
      {
        name: "Pantoprazole",
        genericName: "Pantoprazole",
        strength: "40mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Famotidine",
        genericName: "Famotidine",
        strength: "20mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Aluminum Hydroxide",
        genericName: "Aluminum Hydroxide",
        strength: "500mg",
        form: "Suspension",
        price: 100,
      },
      {
        name: "Metoclopramide",
        genericName: "Metoclopramide",
        strength: "10mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Buscopan",
        genericName: "Hyoscine",
        strength: "10mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Loperamide",
        genericName: "Loperamide",
        strength: "2mg",
        form: "Capsule",
        price: 60,
      },
      {
        name: "Bisacodyl",
        genericName: "Bisacodyl",
        strength: "5mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Lactulose",
        genericName: "Lactulose",
        strength: "10g/15ml",
        form: "Syrup",
        price: 200,
      },
      {
        name: "Senna",
        genericName: "Senna",
        strength: "8.6mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Metformin",
        genericName: "Metformin",
        strength: "500mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Metformin",
        genericName: "Metformin",
        strength: "850mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Gliclazide",
        genericName: "Gliclazide",
        strength: "80mg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Glimepiride",
        genericName: "Glimepiride",
        strength: "2mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Sitagliptin",
        genericName: "Sitagliptin",
        strength: "100mg",
        form: "Tablet",
        price: 300,
      },
      {
        name: "Insulin Regular",
        genericName: "Insulin Regular",
        strength: "100IU/ml",
        form: "Injection",
        price: 500,
      },
      {
        name: "Insulin NPH",
        genericName: "Insulin NPH",
        strength: "100IU/ml",
        form: "Injection",
        price: 500,
      },
      {
        name: "Dextrose 5%",
        genericName: "Dextrose",
        strength: "5%",
        form: "Solution",
        price: 80,
      },
      {
        name: "Dextrose 25%",
        genericName: "Dextrose",
        strength: "25%",
        form: "Solution",
        price: 150,
      },
      {
        name: "Normal Saline",
        genericName: "Sodium Chloride",
        strength: "0.9%",
        form: "Solution",
        price: 50,
      },
      {
        name: "Ringer's Lactate",
        genericName: "Ringer's Lactate",
        strength: "1L",
        form: "Solution",
        price: 80,
      },
      {
        name: "Potassium Chloride",
        genericName: "Potassium Chloride",
        strength: "600mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "B-Complex",
        genericName: "B-Complex",
        strength: "Various",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Vitamin C",
        genericName: "Ascorbic Acid",
        strength: "500mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Vitamin E",
        genericName: "Tocopherol",
        strength: "400IU",
        form: "Capsule",
        price: 80,
      },
      {
        name: "Zinc",
        genericName: "Zinc Sulfate",
        strength: "20mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Iron Polymaltose",
        genericName: "Iron Polymaltose",
        strength: "100mg",
        form: "Tablet",
        price: 120,
      },
      {
        name: "Folic Acid",
        genericName: "Folic Acid",
        strength: "5mg",
        form: "Tablet",
        price: 40,
      },
      {
        name: "Levothyroxine",
        genericName: "Levothyroxine",
        strength: "100mcg",
        form: "Tablet",
        price: 100,
      },
      {
        name: "Hydrocortisone",
        genericName: "Hydrocortisone",
        strength: "10mg",
        form: "Tablet",
        price: 80,
      },
      {
        name: "Dexamethasone Tab",
        genericName: "Dexamethasone",
        strength: "0.5mg",
        form: "Tablet",
        price: 60,
      },
      {
        name: "Prednisolone",
        genericName: "Prednisolone",
        strength: "5mg",
        form: "Tablet",
        price: 50,
      },
      {
        name: "Silver Sulfadiazine",
        genericName: "Silver Sulfadiazine",
        strength: "1%",
        form: "Cream",
        price: 150,
      },
      {
        name: "Mupirocin",
        genericName: "Mupirocin",
        strength: "2%",
        form: "Ointment",
        price: 200,
      },
      {
        name: "Clotrimazole",
        genericName: "Clotrimazole",
        strength: "1%",
        form: "Cream",
        price: 100,
      },
      {
        name: "Povidone-Iodine",
        genericName: "Povidone-Iodine",
        strength: "10%",
        form: "Solution",
        price: 80,
      },
      {
        name: "Calamine Lotion",
        genericName: "Calamine",
        strength: "15%",
        form: "Lotion",
        price: 60,
      },
      {
        name: "Benzoyl Peroxide",
        genericName: "Benzoyl Peroxide",
        strength: "5%",
        form: "Gel",
        price: 150,
      },
    ],
  },
};

async function seedDepartmentMedicines() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing medicines
    await Medicine.deleteMany({});
    console.log("🗑️  Cleared existing medicines");

    let totalAdded = 0;

    // Add medicines from each department
    for (const [department, data] of Object.entries(departmentMedicines)) {
      console.log(
        `\n📦 Adding ${data.medicines.length} medicines from ${department}...`,
      );

      let addedCount = 0;
      let skippedCount = 0;

      for (const med of data.medicines) {
        try {
          await Medicine.create({
            ...med,
            category: data.category,
            manufacturer: "Various",
            stockQuantity: Math.floor(Math.random() * 300) + 200, // 200-500 initial stock
            reorderLevel: 100,
            expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // 1 year from now
            batchNumber: `BATCH-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
          });
          totalAdded++;
          addedCount++;
        } catch (err) {
          if (err.code === 11000) {
            // Duplicate key - skip
            skippedCount++;
            console.log(
              `⚠️  Skipped duplicate: ${med.name} ${med.strength} ${med.form}`,
            );
          } else {
            throw err;
          }
        }
      }

      console.log(
        `✅ Added ${addedCount} ${department} medicines (skipped ${skippedCount} duplicates)`,
      );
    }

    console.log(
      `\n🎉 Successfully added ${totalAdded} medicines to inventory!`,
    );
    console.log("📊 Minimum stock level set to 100 for all medicines");

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding medicines:", error);
    process.exit(1);
  }
}

seedDepartmentMedicines();
